---
###############################################################################
# 1. Proxy (HA / LB / Router)
###############################################################################
- name: Build Proxy (HA / LB / Router)
  hosts: proxy
  gather_facts: true
  become: true

  pre_tasks:
    - name: Load proxy non-secret vars
      ansible.builtin.include_vars:
        file: "{{ playbook_dir }}/group_vars/proxy/main.yml"

    - name: Load proxy secret vars (vault)
      ansible.builtin.include_vars:
        file: "{{ proxy_vault_vars_file }}"
      no_log: true

  roles:
    - proxy

  tags: ['proxy']


###############################################################################
# 2. etcd cluster
###############################################################################
- name: Build etcd cluster
  hosts: etcd
  gather_facts: true
  become: true

  pre_tasks:
    - name: Load etcd non-secret vars
      ansible.builtin.include_vars:
        file: "{{ playbook_dir }}/group_vars/etcd/main.yml"

  roles:
    - etcd

  tags: ['etcd']


###############################################################################
# 3. PostgreSQL / Patroni infra (db_cluster)
###############################################################################
- name: Build DB Infra (PostgreSQL / Patroni)
  hosts: db_cluster
  serial: 1
  gather_facts: true
  become: true

  pre_tasks:
    - name: Load DB non-secret vars
      ansible.builtin.include_vars:
        file: "{{ playbook_dir }}/group_vars/db/main.yml"

    - name: Load DB secret vars (vault)
      ansible.builtin.include_vars:
        file: "{{ db_vault_vars_file }}"
      no_log: true

  roles:
    - db

  tags: ['db_infra', 'db']


###############################################################################
# 4. SSH bootstrap (dbb -> db_cluster)
# - pgBackRest가 follow-primary로 동작하려면,
#   dbb -> db-a/db-s 로 root SSH가 "항상" 무중단으로 되어 있어야 함
###############################################################################
- name: Sync SSH keys (dbb -> db_cluster)
  hosts: db_backup
  gather_facts: false
  become: true

  pre_tasks:
    - name: Load DB non-secret vars
      ansible.builtin.include_vars:
        file: "{{ playbook_dir }}/group_vars/db/main.yml"

  roles:
    - ssh

  tags: ['ssh', 'bootstrap']


###############################################################################
# 5. Backup / Storage (NFS server + backup client pgBackRest config)
# - backup_server: storageVM (NFS export)
# - backup_clients: dbb (pgBackRest client + repo mount + config)
###############################################################################
- name: Build Backup / Storage
  hosts: backup_server:backup_clients
  gather_facts: true
  become: true

  pre_tasks:
    - name: Load DB non-secret vars
      ansible.builtin.include_vars:
        file: "{{ playbook_dir }}/group_vars/db/main.yml"

    - name: Load DB secret vars (vault)
      ansible.builtin.include_vars:
        file: "{{ db_vault_vars_file }}"
      no_log: true

  roles:
    - backup

  tags: ['backup']


###############################################################################
# 6. DB Objects (schema/tables/grants) - dbT
###############################################################################
- name: Build DB Objects (dbT)
  hosts: db_cluster
  gather_facts: false
  become: true

  pre_tasks:
    - name: Load DB non-secret vars
      ansible.builtin.include_vars:
        file: "{{ playbook_dir }}/group_vars/db/main.yml"

    - name: Load DB secret vars (vault)
      ansible.builtin.include_vars:
        file: "{{ db_vault_vars_file }}"
      no_log: true

  roles:
    - dbT

  tags: ['dbT']

