---
- name: Build Proxy (HA / LB / Router)
  hosts: proxy
  gather_facts: true
  become: true

  pre_tasks:
    - name: Load proxy non-secret vars
      ansible.builtin.include_vars:
        file: "{{ playbook_dir }}/group_vars/proxy/main.yml"

    - name: Load proxy secret vars (vault)
      ansible.builtin.include_vars:
        file: "{{ proxy_vault_vars_file }}"

  roles:
    - proxy


- name: Build DB (PostgreSQL / Patroni / etcd / Backup)
  hosts: db
  gather_facts: true
  become: true

  pre_tasks:
    - name: Load DB non-secret vars
      ansible.builtin.include_vars:
        file: "{{ playbook_dir }}/group_vars/db/main.yml"

    - name: Load DB secret vars (vault)
      ansible.builtin.include_vars:
        file: "{{ db_vault_vars_file }}"

  roles:
    - db

